'use client';

import { useState, useCallback, useEffect } from 'react';
import { Play, Loader2, CloudUpload, FileDown, Clock, CheckCircle2, AlertCircle } from 'lucide-react';
import { FeedbackButtons } from './FeedbackButtons';

interface InsightCardProps {
  featureId: string;
  insightType: string;
  title: string;
  icon: React.ReactNode;
  onRun: () => Promise<string>;
  /** If provided, calling .triggerRun() from parent will programmatically run the card */
  controlRef?: React.MutableRefObject<{ triggerRun?: () => void }>;
  /** localStorage key to persist last-run timestamp across sessions */
  persistKey?: string;
}

export function InsightCard({ featureId, insightType, title, icon, onRun, controlRef, persistKey }: InsightCardProps) {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<string | null>(null);
  const [lastRun, setLastRun] = useState<Date | null>(() => {
    if (!persistKey || typeof window === 'undefined') return null;
    const saved = localStorage.getItem(persistKey);
    return saved ? new Date(saved) : null;
  });
  const [disabled, setDisabled] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [driveStatus, setDriveStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle');

  const run = useCallback(async () => {
    setLoading(true);
    setError(null);
    setDisabled(true);
    setDriveStatus('idle');
    try {
      const text = await onRun();
      setResult(text);
      const now = new Date();
      setLastRun(now);
      if (persistKey) localStorage.setItem(persistKey, now.toISOString());
    } catch (e: any) {
      setError(e.message ?? 'Analysis failed. Check your API key in Settings or try again.');
    } finally {
      setLoading(false);
      setTimeout(() => setDisabled(false), 30_000);
    }
  }, [onRun, persistKey]);

  // Expose triggerRun to parent via controlRef
  useEffect(() => {
    if (controlRef) controlRef.current.triggerRun = run;
  }, [controlRef, run]);

  const downloadPDF = () => {
    if (!result) return;
    const dateStr = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title>
<style>
  body { font-family: Georgia, serif; max-width: 700px; margin: 40px auto; color: #1e293b; line-height: 1.7; }
  h1 { font-size: 1.4rem; border-bottom: 2px solid #3b82f6; padding-bottom: 8px; color: #1d4ed8; }
  p { white-space: pre-line; font-size: 0.95rem; }
  .meta { color: #64748b; font-size: 0.8rem; margin-bottom: 24px; }
  @media print { body { margin: 20px; } }
</style></head>
<body>
  <h1>${title}</h1>
  <div class="meta">Generated by FAIN — Money Mngr &nbsp;|&nbsp; ${dateStr}</div>
  <p>${result.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</p>
</body></html>`;
    const w = window.open('', '_blank');
    if (!w) return;
    w.document.write(html);
    w.document.close();
    w.focus();
    setTimeout(() => { w.print(); }, 400);
  };

  const saveToDrive = async () => {
    if (!result) return;
    setDriveStatus('saving');
    try {
      const res = await fetch('/api/fain/save-to-drive', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ insightId: featureId, content: result }),
      });
      if (!res.ok) throw new Error((await res.json()).error ?? 'Save failed');
      setDriveStatus('saved');
      setTimeout(() => setDriveStatus('idle'), 3000);
    } catch (_e) {
      setDriveStatus('error');
      setTimeout(() => setDriveStatus('idle'), 3000);
    }
  };

  return (
    <div className="rounded-xl border border-gray-200 bg-white p-4 space-y-3">
      {/* Title row */}
      <div className="flex items-center gap-2">
        <span>{icon}</span>
        <span className="font-medium text-gray-800 flex-1">{title}</span>
        {lastRun && (
          <span className="flex items-center gap-1 text-xs text-gray-400">
            <Clock size={11} />
            {lastRun.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}
          </span>
        )}
      </div>

      {/* Result */}
      {result && (
        <div className="text-sm text-gray-700 leading-relaxed whitespace-pre-line bg-gray-50 rounded-lg p-3">
          {result}
        </div>
      )}

      {error && (
        <div className="text-sm text-red-600 bg-red-50 rounded-lg p-3">{error}</div>
      )}

      {!lastRun && !loading && (
        <p className="text-xs text-gray-400">Never run — click ▶ Run to analyse</p>
      )}

      {/* Action row */}
      <div className="flex flex-wrap items-center gap-2">
        <button
          onClick={run}
          disabled={loading || disabled}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-500 disabled:opacity-50 disabled:cursor-not-allowed text-sm text-white font-medium transition"
        >
          {loading ? (
            <>
              <Loader2 size={14} className="animate-spin" />
              Analysing…
            </>
          ) : (
            <>
              <Play size={14} />
              Run
            </>
          )}
        </button>

        {result && (
          <>
            <button
              onClick={saveToDrive}
              disabled={driveStatus === 'saving'}
              className="flex items-center gap-1 px-3 py-1.5 rounded-lg border border-gray-200 hover:border-blue-400 text-xs text-gray-600 hover:text-blue-600 transition disabled:opacity-50"
              title="Save to Google Drive"
            >
              {driveStatus === 'saving' && <Loader2 size={13} className="animate-spin" />}
              {driveStatus === 'saved' && <CheckCircle2 size={13} className="text-green-600" />}
              {driveStatus === 'error' && <AlertCircle size={13} className="text-red-600" />}
              {driveStatus === 'idle' && <CloudUpload size={13} />}
              {driveStatus === 'saving' ? 'Saving…' : driveStatus === 'saved' ? 'Saved ✓' : driveStatus === 'error' ? 'Failed' : 'Save to Drive'}
            </button>

            <button
              onClick={downloadPDF}
              className="flex items-center gap-1 px-3 py-1.5 rounded-lg border border-gray-200 hover:border-gray-300 text-xs text-gray-600 transition"
              title="Download as PDF"
            >
              <FileDown size={13} /> Download PDF
            </button>
          </>
        )}
      </div>

      {/* Feedback */}
      {result && (
        <FeedbackButtons
          featureId={featureId}
          insightType={insightType}
          insightSummary={result}
        />
      )}
    </div>
  );
}
